# Generated by /feature-spec
# Feature: NATS Configuration
# Stack: python
# Assumptions: 6 (see nats-configuration_assumptions.yaml)
# Generated: 2026-04-08T00:00:00Z

@nats-configuration
Feature: NATS Configuration
  As a fleet service developer
  I want connection settings managed via pydantic-settings with environment variable overrides
  So that every service configures its NATS connection consistently without hardcoded values

  Background:
    Given the NATSConfig settings class is available

  # Why: Most common case -- zero-config local development
  @key-example @smoke
  Scenario: Default configuration connects to localhost
    Given no NATS-related environment variables are set
    When I create a NATSConfig with no arguments
    Then url should be "nats://localhost:4222"
    And connect_timeout should be 5.0
    And reconnect_time_wait should be 2.0
    And max_reconnect_attempts should be 60
    And name should be "nats-core-client"

  # Why: Primary deployment override -- all services read NATS_URL from env
  @key-example @smoke
  Scenario: Environment variable overrides the default URL
    Given NATS_URL is set to "nats://gb10.tail:4222"
    When I create a NATSConfig
    Then url should be "nats://gb10.tail:4222"

  # Why: Account-based auth for multi-tenant NATS -- user/password from env
  @key-example
  Scenario: Configuring user and password authentication from environment
    Given NATS_USER is set to "appmilla"
    And NATS_PASSWORD is set to "s3cret"
    When I create a NATSConfig
    Then user should be "appmilla"
    And password should be "s3cret"

  # Why: NKey credentials for production -- more secure than user/password
  @key-example
  Scenario: Configuring NKey credentials file from environment
    Given NATS_CREDS_FILE is set to "/etc/nats/appmilla.creds"
    When I create a NATSConfig
    Then creds_file should be "/etc/nats/appmilla.creds"

  # Why: Explicit constructor overrides -- used in tests and one-off scripts
  @key-example
  Scenario: Constructor arguments override defaults
    When I create a NATSConfig with url "nats://test:4222" and connect_timeout 1.0
    Then url should be "nats://test:4222"
    And connect_timeout should be 1.0
    And all other fields should retain their defaults

  # Why: Just-inside boundary -- connect_timeout must be non-negative
  @boundary
  Scenario: Connect timeout at zero is accepted
    When I create a NATSConfig with connect_timeout 0.0
    Then connect_timeout should be 0.0

  # Why: Just-outside boundary -- negative timeout is meaningless
  @boundary @negative
  Scenario: Negative connect timeout is rejected
    When I create a NATSConfig with connect_timeout -1.0
    Then it should raise a validation error
    And the error should indicate connect_timeout must be non-negative

  # Why: Just-inside boundary -- reconnect time wait must be non-negative
  @boundary
  Scenario: Reconnect time wait at zero is accepted
    When I create a NATSConfig with reconnect_time_wait 0.0
    Then reconnect_time_wait should be 0.0

  # Why: Just-outside boundary -- negative reconnect wait is meaningless
  @boundary @negative
  Scenario: Negative reconnect time wait is rejected
    When I create a NATSConfig with reconnect_time_wait -1.0
    Then it should raise a validation error
    And the error should indicate reconnect_time_wait must be non-negative

  # Why: Just-inside boundary -- max reconnect attempts must be non-negative
  @boundary
  Scenario: Max reconnect attempts at zero means no retries
    When I create a NATSConfig with max_reconnect_attempts 0
    Then max_reconnect_attempts should be 0

  # Why: Just-outside boundary -- negative retry count is meaningless
  @boundary @negative
  Scenario: Negative max reconnect attempts is rejected
    When I create a NATSConfig with max_reconnect_attempts -1
    Then it should raise a validation error
    And the error should indicate max_reconnect_attempts must be non-negative

  # Why: URL must be a valid NATS URI -- reject garbage input at config time
  # [ASSUMPTION: confidence=medium] URL must start with nats:// or tls:// per nats-py convention
  @negative
  Scenario: Invalid URL scheme is rejected
    When I create a NATSConfig with url "http://localhost:4222"
    Then it should raise a validation error
    And the error should indicate the URL scheme must be nats or tls

  # Why: Empty URL is never valid -- catch misconfigured environments early
  @negative
  Scenario: Empty URL is rejected
    When I create a NATSConfig with url ""
    Then it should raise a validation error
    And the error should indicate the URL must not be empty

  # Why: Client name must not be empty -- NATS monitoring relies on it
  # [ASSUMPTION: confidence=medium] Client name is required for observability in NATS dashboard
  @negative
  Scenario: Empty client name is rejected
    When I create a NATSConfig with name ""
    Then it should raise a validation error
    And the error should indicate the client name must not be empty

  # Why: Partial auth config is a misconfiguration -- catch it early
  # [ASSUMPTION: confidence=low] Providing user without password (or vice versa) should be an error
  @negative
  Scenario: User without password is rejected
    Given NATS_USER is set to "appmilla"
    And NATS_PASSWORD is not set
    When I create a NATSConfig
    Then it should raise a validation error
    And the error should indicate both user and password must be provided together

  # Why: Environment variables take precedence over constructor defaults but not explicit args
  @edge-case
  Scenario: Environment variable precedence over defaults
    Given NATS_URL is set to "nats://env-server:4222"
    When I create a NATSConfig with no arguments
    Then url should be "nats://env-server:4222"

  # Why: Multiple config instances should be independent -- no shared mutable state
  @edge-case
  Scenario: Multiple NATSConfig instances are independent
    Given NATS_URL is set to "nats://shared:4222"
    When I create two NATSConfig instances
    And I modify the url on the first instance
    Then the second instance url should still be "nats://shared:4222"

  # Why: .env file support is a pydantic-settings feature -- verify it works
  # [ASSUMPTION: confidence=medium] NATSConfig reads from .env files via pydantic-settings default behaviour
  @edge-case
  Scenario: Configuration loads from dotenv file
    Given a .env file containing NATS_URL="nats://dotenv-server:4222"
    When I create a NATSConfig
    Then url should be "nats://dotenv-server:4222"

  # Why: Config should be serialisable for logging/debugging without leaking secrets
  # [ASSUMPTION: confidence=low] Password and creds_file should be excluded from repr/str output
  @edge-case
  Scenario: Sensitive fields are masked in string representation
    Given a NATSConfig with user "admin" and password "s3cret"
    When I convert the config to a string representation
    Then the password should be masked or excluded
    And the user should be visible

  # Why: Configs get logged in production -- secrets must not leak into log output
  @edge-case
  Scenario: Password is not exposed when config is serialised to dict
    Given a NATSConfig with user "admin" and password "s3cret"
    When I serialise the config to a dictionary
    Then the password value should be masked as "**********" or excluded entirely

  # Why: Creds file path should be validated to prevent directory traversal
  @edge-case @negative
  Scenario: Creds file with path traversal is rejected
    When I create a NATSConfig with creds_file "../../etc/passwd"
    Then it should raise a validation error
    And the error should indicate the credentials path is invalid

  # Why: NATSConfig must produce kwargs that nats-py Client.connect() accepts directly
  @edge-case
  Scenario: Config produces valid nats-py connection kwargs
    Given a NATSConfig with url "nats://gb10.tail:4222" and connect_timeout 10.0
    When I convert the config to connection kwargs
    Then the result should contain servers as a list with "nats://gb10.tail:4222"
    And the result should contain connect_timeout as 10.0
    And the result should be accepted by nats-py connect

  # Why: Ambiguous auth config -- user/password and creds_file are mutually exclusive
  # [ASSUMPTION: confidence=low] Providing both password auth and creds_file is a misconfiguration
  @edge-case @negative
  Scenario: Providing both password auth and creds file is rejected
    Given NATS_USER is set to "admin"
    And NATS_PASSWORD is set to "s3cret"
    And NATS_CREDS_FILE is set to "/etc/nats/appmilla.creds"
    When I create a NATSConfig
    Then it should raise a validation error
    And the error should indicate that password auth and credentials file are mutually exclusive
