# Generated by /feature-spec
# Feature: NATS Client
# Stack: python
# Assumptions: 4 (see nats-client_assumptions.yaml)
# Generated: 2026-04-08T00:00:00Z

@nats-client
Feature: NATS Client
  As a fleet service developer
  I want a typed publish/subscribe wrapper with automatic envelope handling
  So that services can exchange strongly-typed events without manual serialisation or topic string construction

  Background:
    Given a NATSClient configured with default settings
    And the NATS connection is established

  # Why: Core publish path -- typed event is wrapped in envelope and sent to the correct topic
  @key-example @smoke
  Scenario: Publishing a typed event wraps it in a MessageEnvelope
    When I publish a BuildCompletePayload for feature "FEAT-001"
    Then the client should publish to "pipeline.build-complete.FEAT-001"
    And the message should be a valid JSON-serialised MessageEnvelope
    And the envelope source_id should identify the publisher
    And the envelope event_type should be BUILD_COMPLETE
    And the envelope payload should contain the BuildCompletePayload fields

  # Why: Core subscribe path -- incoming messages are deserialised into typed envelopes
  @key-example @smoke
  Scenario: Subscribing with a typed handler receives deserialised envelopes
    Given I subscribe to build complete events for feature "FEAT-001"
    When a BUILD_COMPLETE message arrives on the corresponding topic
    Then the handler should receive a deserialised MessageEnvelope
    And the envelope payload should be parseable as BuildCompletePayload

  # Why: Multi-tenancy -- project-scoped publish prefixes topics and sets envelope project field
  @key-example @smoke
  Scenario: Project-scoped publish prefixes the topic
    When I publish a BuildCompletePayload for feature "FEAT-001" with project "finproxy"
    Then the topic should be "finproxy.pipeline.build-complete.FEAT-001"
    And the envelope project field should be "finproxy"

  # Why: Correlation -- publish must propagate correlation_id for request chains
  @key-example
  Scenario: Publishing with a correlation ID includes it in the envelope
    When I publish a BuildCompletePayload with correlation_id "session-abc-123"
    Then the envelope correlation_id should be "session-abc-123"
    And the envelope message_id should be a distinct value

  # Why: Fleet registration -- agent self-announces on startup via convenience method
  @key-example @smoke
  Scenario: Registering an agent publishes to the fleet register topic
    Given an AgentRegistrationPayload for agent "product-owner-agent"
    When I call register_agent with the payload
    Then the client should publish to "fleet.register"
    And the envelope event_type should be AGENT_REGISTER
    And the payload should include the agent's declared intent capabilities

  # Why: Fleet heartbeat -- periodic liveness signal via convenience method
  @key-example
  Scenario: Sending a heartbeat publishes to the agent-specific heartbeat topic
    Given an AgentHeartbeatPayload for agent "ideation-agent"
    When I call heartbeat with the payload
    Then the client should publish to "fleet.heartbeat.ideation-agent"
    And the envelope event_type should be AGENT_HEARTBEAT

  # Why: Fleet deregistration -- graceful shutdown via convenience method
  @key-example
  Scenario: Deregistering an agent publishes to the fleet deregister topic
    When I call deregister_agent with agent_id "youtube-planner" and reason "shutdown"
    Then the client should publish to "fleet.deregister"
    And the envelope event_type should be AGENT_DEREGISTER
    And the payload reason should be "shutdown"

  # Why: Agent-to-agent tool invocation -- request-reply pattern for remote tool calls
  @key-example
  Scenario: Calling a remote agent tool uses request-reply
    When I call call_agent_tool with agent_id "guardkit-factory" and tool_name "lint"
    Then the client should publish a request to "agents.guardkit-factory.tools.lint"
    And it should await a reply from the target agent

  # Why: Just-inside boundary -- empty payload dict is valid (minimal event)
  @boundary
  Scenario: Publishing with an empty payload dictionary succeeds
    Given an event type that accepts an empty payload
    When I publish the event with an empty payload
    Then the publish should succeed
    And the envelope payload should be an empty dictionary

  # Why: Just-inside boundary -- single-character source_id is the minimum valid identifier
  @boundary
  Scenario: Client with a single-character source ID publishes successfully
    Given a NATSClient with source_id "x"
    When I publish any typed event
    Then the envelope source_id should be "x"

  # Why: Just-outside boundary -- empty source_id must be rejected at client creation
  @boundary @negative
  Scenario: Creating a client with an empty source ID is rejected
    When I create a NATSClient with source_id ""
    Then it should raise a validation error
    And the error should indicate source_id must not be empty

  # Why: Just-inside boundary -- subscribing to a wildcard topic captures all matching subjects
  @boundary
  Scenario: Subscribing to a wildcard topic receives messages from all matching subjects
    Given I subscribe to all pipeline events using the wildcard topic
    When messages arrive on "pipeline.build-started.FEAT-001" and "pipeline.build-complete.FEAT-002"
    Then the handler should receive both messages as deserialised envelopes

  # Why: Just-inside boundary -- topic with maximum segment depth resolves correctly
  # [ASSUMPTION: confidence=medium] Approval topics have the deepest nesting: agents.approval.{agent_id}.{task_id}.response
  @boundary
  Scenario: Deeply nested topic template resolves correctly
    When I resolve the approval response topic with agent_id "jarvis" and task_id "task-99"
    Then the resolved topic should be "agents.approval.jarvis.task-99.response"

  # Why: Just-outside boundary -- missing template variables must raise an error, not produce partial topics
  @boundary @negative
  Scenario: Publishing with missing topic template variables is rejected
    When I attempt to publish to a topic template without providing all required variables
    Then it should raise an error
    And the error should indicate the missing template variable

  # Why: Publishing on a disconnected client must fail clearly, not silently drop messages
  @negative @smoke
  Scenario: Publishing on a disconnected client raises an error
    Given a NATSClient that is not connected
    When I attempt to publish a typed event
    Then it should raise a connection error
    And the error should indicate the client is not connected

  # Why: Subscribing on a disconnected client must fail, not appear to succeed silently
  @negative
  Scenario: Subscribing on a disconnected client raises an error
    Given a NATSClient that is not connected
    When I attempt to subscribe to a topic
    Then it should raise a connection error

  # Why: Malformed incoming messages must not crash the subscriber
  @negative
  Scenario: Receiving invalid JSON on a subscribed topic does not crash the handler
    Given I subscribe to build complete events for feature "FEAT-001"
    When a message with invalid JSON arrives on the topic
    Then the handler should not crash
    And the malformed message should be reported as an error

  # Why: Incoming message with wrong event type must be handled gracefully
  @negative
  Scenario: Receiving an envelope with an unexpected event type is handled gracefully
    Given I subscribe to build complete events for feature "FEAT-001"
    When an envelope with event_type BUILD_FAILED arrives on the topic
    Then the handler should not crash
    And the unexpected event should be reported or ignored

  # Why: Request-reply timeout -- tool call to an unresponsive agent must not hang indefinitely
  # [ASSUMPTION: confidence=medium] Tool call timeout defaults to 30 seconds per common RPC convention
  @negative
  Scenario: Agent tool call times out when no reply is received
    When I call call_agent_tool with agent_id "offline-agent" and tool_name "test"
    And no reply arrives within the timeout period
    Then the call should raise a timeout error
    And the error should indicate the target agent did not respond

  # Why: Double-connect must not silently create multiple connections
  @negative
  Scenario: Connecting an already-connected client raises an error or is idempotent
    Given a NATSClient that is already connected
    When I call connect again
    Then it should either raise an error or be safely idempotent
    And there should not be duplicate underlying connections

  # Why: Connection resilience -- transient NATS outages must not crash the client permanently
  @edge-case @smoke
  Scenario: Client reconnects automatically after a transient disconnection
    Given a connected NATSClient
    When the NATS server becomes temporarily unavailable
    And then becomes available again
    Then the client should reconnect automatically
    And previously registered subscriptions should resume receiving messages

  # Why: Graceful shutdown -- subscriptions must be drained before disconnect to avoid message loss
  @edge-case @smoke
  Scenario: Graceful disconnect drains all active subscriptions
    Given a connected NATSClient with active subscriptions
    When I call disconnect
    Then all subscriptions should be drained before the connection closes
    And the connection should close cleanly
    And no in-flight messages should be lost

  # Why: Concurrent publishes -- the client must be safe for use from multiple async tasks
  @edge-case
  Scenario: Concurrent publishes from multiple tasks do not corrupt messages
    Given a connected NATSClient
    When I publish 50 events concurrently from separate async tasks
    Then all 50 messages should arrive at the NATS server
    And each message should be a valid MessageEnvelope
    And no messages should be interleaved or corrupted

  # Why: Multiple subscriptions to the same topic -- both handlers must receive messages
  @edge-case
  Scenario: Multiple handlers on the same topic all receive the message
    Given two handlers subscribed to the same topic
    When a message arrives on that topic
    Then both handlers should receive the deserialised envelope

  # Why: Fleet registry read -- the KV-backed registry must return all registered agents
  @edge-case
  Scenario: Reading the fleet registry returns all registered agents
    Given three agents have registered via register_agent
    When I call get_fleet_registry
    Then the result should contain all three agents keyed by agent_id
    And each entry should be a valid AgentRegistrationPayload

  # Why: Fleet watcher -- watch_fleet must deliver registration and deregistration events in real time
  @edge-case
  Scenario: Watching the fleet receives registration and deregistration events
    Given I am watching the fleet via watch_fleet
    When an agent registers and then deregisters
    Then the watcher callback should receive the registration event
    And then the deregistration event in order

  # Why: Envelope defaults must be populated by the client, not by the caller
  @edge-case
  Scenario: Published envelope has auto-generated message_id and timestamp
    When I publish any typed event without specifying message_id or timestamp
    Then the published envelope should contain a valid UUID v4 message_id
    And the timestamp should be within 1 second of now in UTC
    And the version should be "1.0"

  # Why: Payload must not be able to override envelope-level fields during serialisation
  @edge-case
  Scenario: Payload containing envelope-level field names does not override the envelope
    Given a payload dictionary containing a key "source_id" with value "attacker"
    When I publish the event with source_id "legitimate-agent"
    Then the envelope source_id should be "legitimate-agent"
    And the payload "source_id" key should remain in the payload only

  # Why: User-controlled topic segments must not inject NATS wildcards that widen subscription scope
  @edge-case @negative
  Scenario: Topic resolution rejects wildcard characters in segment values
    When I attempt to publish with agent_id "evil.>" or feature_id "FEAT.*"
    Then it should raise a validation error
    And the error should indicate that wildcard characters are not allowed in topic segment values

  # Why: Simultaneous register and deregister must not leave KV in an inconsistent state
  @edge-case
  Scenario: Simultaneous registration and deregistration for the same agent resolves consistently
    When register_agent and deregister_agent are called concurrently for agent "flaky-agent"
    Then the fleet registry should contain either the agent or not
    And the KV state should be consistent with the last operation that completed

  # Why: Messages published during a reconnection window must not be silently dropped
  @edge-case
  Scenario: Publishing during reconnection either queues or fails clearly
    Given a connected NATSClient
    When the NATS server disconnects and the client is reconnecting
    And I attempt to publish a typed event during the reconnection window
    Then the publish should either queue the message for delivery after reconnection
    Or raise a clear error indicating the connection is not yet restored

  # Why: Slow consumer warnings from NATS must not crash the client
  @edge-case
  Scenario: Client handles slow consumer backpressure without crashing
    Given a connected NATSClient with a subscription
    When the NATS server signals slow consumer backpressure
    Then the client should not crash
    And it should report the backpressure condition as a warning

  # Why: KV bucket unavailability must fail with a clear error, not hang indefinitely
  @edge-case @negative
  Scenario: Fleet registry read fails clearly when KV bucket is unavailable
    Given the agent-registry KV bucket is not available
    When I call get_fleet_registry
    Then it should raise an error indicating the registry is unavailable
    And the call should not hang indefinitely
