# Generated by /feature-spec
# Feature: Fleet Registration
# Stack: python
# Assumptions: 8 (see fleet-registration_assumptions.yaml)
# Generated: 2026-04-08T00:00:00Z

@fleet-registration
Feature: Fleet Registration
  As a fleet operator
  I want agents to self-announce their capabilities on startup and maintain liveness via heartbeats
  So that the router can dynamically discover agents and build a KV-backed routing table without code changes

  Background:
    Given the NATS connection is established
    And the "agent-registry" KV bucket exists

  # Why: Core registration path -- agent publishes its capability manifest and appears in the routing table
  @key-example @smoke
  Scenario: Agent registers on startup
    Given the Product Owner Agent is starting
    When it publishes an AgentRegistrationPayload to fleet.register
    Then the agent should appear in the "agent-registry" KV bucket with key "product-owner-agent"
    And the registration should include agent_id "product-owner-agent"
    And it should declare at least one intent capability
    And each declared intent should have a confidence score between 0.0 and 1.0

  # Why: Signal words are the basis for Jarvis intent classification -- they must be present and meaningful
  @key-example
  Scenario: Registration includes signal words for intent matching
    Given the Ideation Agent registers with the fleet
    Then its registration should declare intent "ideate" with signals including "explore" and "brainstorm"
    And the intent "ideate" should have confidence of at least 0.8

  # Why: Heartbeats are the liveness mechanism -- registration without heartbeating is incomplete
  # [ASSUMPTION: confidence=high] Heartbeat interval is 30 seconds per system spec
  @key-example @smoke
  Scenario: Agent begins heartbeating after registration
    Given the Ideation Agent has registered with the fleet
    When 30 seconds elapse
    Then the agent should have published a heartbeat to "fleet.heartbeat.ideation-agent"
    And the heartbeat should include current queue_depth and active_tasks
    And status should be one of "ready", "busy", "degraded", or "draining"

  # Why: Clean shutdown path -- agents that exit gracefully should be removed immediately, not wait for timeout
  @key-example @smoke
  Scenario: Graceful deregistration removes agent from routing table
    Given "youtube-planner" is registered in the fleet
    When it publishes an AgentDeregistrationPayload with reason "shutdown"
    Then "youtube-planner" should be removed from the "agent-registry" KV bucket
    And the router should no longer dispatch requests to "youtube-planner"

  # Why: The core CAN bus value proposition -- zero router code changes when the fleet grows
  @key-example
  Scenario: New agent is auto-discovered without router changes
    Given the router is running with 3 registered agents
    When a new agent "product-owner-agent" publishes a registration to fleet.register
    Then the router should add it to the routing table
    And no code changes to the router were required

  # Why: KV-backed routing table is the key persistence guarantee from ADR-004
  @key-example
  Scenario: Registration survives router restart via KV persistence
    Given 5 agents are registered in the "agent-registry" KV bucket
    When the router restarts
    Then all 5 agents should be available in the routing table from KV
    And no agents needed to re-register

  # Why: Confidence 0.0 and 1.0 are valid edge values -- both must be accepted
  @boundary
  Scenario Outline: Confidence score at valid boundaries is accepted
    Given an agent registers with intent "general" at confidence <confidence>
    When the registration is processed
    Then the registration should succeed

    Examples:
      | confidence |
      | 0.0        |
      | 0.5        |
      | 1.0        |

  # Why: Confidence must be strictly within [0.0, 1.0] -- values outside should be rejected at validation
  @boundary @negative
  Scenario Outline: Confidence score outside valid range is rejected
    Given an agent registers with intent "general" at confidence <confidence>
    When the registration is validated
    Then the registration should be rejected
    And the error should indicate confidence must be between 0.0 and 1.0

    Examples:
      | confidence |
      | -0.1       |
      | 1.1        |

  # Why: max_concurrent controls concurrency gating -- zero is meaningless and should be rejected
  @boundary
  Scenario: Agent registers with max_concurrent of 1
    Given an agent registers with max_concurrent 1
    When the registration is processed
    Then the registration should succeed
    And the agent should accept at most 1 concurrent task

  # [ASSUMPTION: confidence=medium] max_concurrent minimum is 1 based on domain logic (0 = useless agent)
  @boundary @negative
  Scenario: Agent registers with max_concurrent of 0
    Given an agent registers with max_concurrent 0
    When the registration is validated
    Then the registration should be rejected
    And the error should indicate max_concurrent must be at least 1

  # [ASSUMPTION: confidence=high] Heartbeat timeout is 90s (3x the 30s interval) per system spec
  @boundary
  Scenario: Heartbeat received at exactly 89 seconds does not trigger timeout
    Given a registered agent with its last heartbeat 89 seconds ago
    When the router checks liveness
    Then the agent should still be marked as available

  @boundary
  Scenario: No heartbeat for exactly 90 seconds triggers timeout
    Given a registered agent with its last heartbeat 90 seconds ago
    When the router checks liveness
    Then the agent should be marked as unavailable

  # [ASSUMPTION: confidence=medium] Agents must declare at least one intent capability
  @boundary @negative
  Scenario: Agent registration with no intent capabilities is rejected
    Given an agent registers with an empty intents list
    When the registration is validated
    Then the registration should be rejected
    And the error should indicate at least one intent capability is required

  # Why: Queue depth 0 is the normal idle state -- must be accepted and used as tiebreaker
  @boundary
  Scenario: Heartbeat with queue depth of zero is valid
    Given a registered agent publishes a heartbeat with queue_depth 0
    When the heartbeat is processed
    Then the agent should be recorded with queue_depth 0
    And the agent should be preferred over agents with higher queue depth for tiebreaking

  # Why: agent_id and name are required -- missing them should fail at the schema level
  @negative
  Scenario Outline: Registration missing required field is rejected
    Given an AgentRegistrationPayload without <field>
    When the registration is validated
    Then the registration should be rejected
    And the error should indicate <field> is required

    Examples:
      | field    |
      | agent_id |
      | name     |
      | template |

  # Why: Re-registration should update, not duplicate -- the KV key is agent_id
  @negative
  Scenario: Re-registration with the same agent_id updates the existing entry
    Given "ideation-agent" is already registered in the fleet
    When a new registration for "ideation-agent" arrives with updated intents
    Then the routing table should contain only one entry for "ideation-agent"
    And the entry should reflect the updated intents

  # Why: Deregistering a non-existent agent should be idempotent, not an error
  @negative
  Scenario: Deregistration for an unknown agent is silently ignored
    Given "phantom-agent" is not registered in the fleet
    When a deregistration for "phantom-agent" is received
    Then no error should be raised
    And the routing table should be unchanged

  # [ASSUMPTION: confidence=medium] Heartbeats from unregistered agents are silently ignored
  @negative
  Scenario: Heartbeat from an unregistered agent is ignored
    Given "ghost-agent" is not registered in the fleet
    When a heartbeat from "ghost-agent" is received
    Then no error should be raised
    And "ghost-agent" should not appear in the routing table

  # Why: Must handle the case where no registered agent can fulfil a request
  @negative
  Scenario: Request with no matching agent intent is not dispatched
    Given registered agents only handle intents "ideate" and "software.build"
    When a request with intent "translate.document" arrives
    Then the request should not be dispatched
    And the requestor should be informed that no capable agent is available

  # Why: Core routing logic -- highest confidence wins
  @edge-case
  Scenario: Confidence-based routing selects the best agent
    Given "ideation-agent" declares intent "ideate" with confidence 0.9
    And "general-purpose-agent" declares intent "ideate" with confidence 0.3
    When a request with intent "ideate" arrives
    Then the router should dispatch to "ideation-agent"

  # Why: When confidence is equal, queue depth is the tiebreaker per ADR-004
  @edge-case
  Scenario: Queue-aware routing breaks confidence ties
    Given "factory-1" declares "software.build" with confidence 1.0 and queue_depth 3
    And "factory-2" declares "software.build" with confidence 1.0 and queue_depth 0
    When a new "software.build" request arrives
    Then the router should dispatch to "factory-2"

  # Why: max_concurrent is the backpressure mechanism -- full agents must not receive more work
  @edge-case
  Scenario: Agent at max_concurrent capacity is skipped for routing
    Given "guardkit-factory" registers with max_concurrent 2 and active_tasks 2
    And "guardkit-factory-2" registers with max_concurrent 2 and active_tasks 0
    When a new "software.build" request arrives
    Then the router should dispatch to "guardkit-factory-2"
    And "guardkit-factory" should not receive the request

  # Why: Liveness detection is the safety net -- crashed agents must be removed from routing
  @edge-case
  Scenario: Heartbeat timeout marks agent unavailable
    Given "architect-agent" is registered and was heartbeating every 30 seconds
    When no heartbeat is received for 90 seconds
    Then the router should mark "architect-agent" as unavailable
    And "architect-agent" should not receive new dispatches

  # [ASSUMPTION: confidence=medium] An agent that resumes heartbeating after timeout automatically returns to available
  @edge-case
  Scenario: Agent recovers from unavailable state by resuming heartbeats
    Given "architect-agent" has been marked unavailable due to heartbeat timeout
    When a new heartbeat from "architect-agent" is received
    Then "architect-agent" should be marked as available again
    And it should be eligible for routing

  # [ASSUMPTION: confidence=low] No authentication mechanism on registration -- any agent can claim any agent_id
  @edge-case @security
  Scenario: Re-registration with an existing agent_id overwrites the previous entry
    Given "product-owner-agent" is registered with intent "product.document" at confidence 0.9
    When a new registration arrives claiming agent_id "product-owner-agent" with different intents
    Then the routing table should reflect the new registration
    And the previous capabilities should be replaced

  # [ASSUMPTION: confidence=medium] Maximum metadata size is 64KB based on NATS KV value size conventions
  @edge-case @security
  Scenario: Registration with excessively large metadata is rejected
    Given an AgentRegistrationPayload with metadata exceeding 64KB
    When the registration is validated
    Then the registration should be rejected
    And the error should indicate metadata exceeds the maximum allowed size

  # Why: Two instances starting at the same time could race on the KV write -- last-write-wins is acceptable
  @edge-case @concurrency
  Scenario: Simultaneous registrations with the same agent_id resolve to last-write-wins
    Given two instances of "guardkit-factory" publish registrations simultaneously
    When both registrations are processed
    Then the routing table should contain exactly one entry for "guardkit-factory"
    And the entry should reflect whichever registration was processed last

  # Why: Race between a heartbeat in-flight and a deregistration -- deregistration should take precedence
  @edge-case @concurrency
  Scenario: Deregistration takes precedence over a concurrent heartbeat
    Given "ideation-agent" is registered and heartbeating
    When a deregistration and a heartbeat for "ideation-agent" arrive simultaneously
    Then "ideation-agent" should be removed from the routing table
    And the heartbeat should not resurrect the agent

  # Why: JetStream or the KV bucket could be temporarily degraded -- registration must handle this gracefully
  @edge-case @integration
  Scenario: Registration fails gracefully when KV bucket is unavailable
    Given the "agent-registry" KV bucket is unavailable
    When an agent publishes a registration to fleet.register
    Then the registration should fail with a retriable error
    And the agent should be able to retry registration when KV recovers

  # Why: Cold start or total fleet failure -- router must not crash when no agents are registered
  @edge-case @integration
  Scenario: Dispatch request with an empty fleet registry returns no capable agent
    Given no agents are registered in the fleet
    When a request with intent "software.build" arrives
    Then the request should not be dispatched
    And the requestor should be informed that no agents are available
