# Generated by /feature-spec
# Feature: Topic Registry
# Stack: python
# Assumptions: 5 (see topic-registry_assumptions.yaml)
# Generated: 2026-04-08T00:00:00Z

@topic-registry
Feature: Topic Registry
  As a fleet service developer
  I want typed constants for all NATS subjects with resolution and project scoping
  So that no service uses magic strings for topic names and all subjects are validated at import time

  Background:
    Given the Topics registry class is available

  # Why: Core pipeline topic resolution -- most common operation in the fleet
  @key-example @smoke
  Scenario: Resolving a pipeline topic with a feature ID
    When I resolve Topics.Pipeline.BUILD_STARTED with feature_id "FEAT-AC1A"
    Then the result should be "pipeline.build-started.FEAT-AC1A"

  # Why: Agent status topic -- used by every agent on every state change
  @key-example @smoke
  Scenario: Resolving an agent status topic with an agent ID
    When I resolve Topics.Agents.STATUS with agent_id "guardkit-factory"
    Then the result should be "agents.status.guardkit-factory"

  # Why: Fleet registration topic -- no placeholders, used as-is
  @key-example @smoke
  Scenario: Fleet registration topic is a fixed string
    When I access Topics.Fleet.REGISTER
    Then the value should be "fleet.register"

  # Why: Jarvis dispatch -- routes intent to a specific agent
  @key-example @smoke
  Scenario: Resolving a Jarvis dispatch topic with an agent name
    When I resolve Topics.Jarvis.DISPATCH with agent "ideation-agent"
    Then the result should be "jarvis.dispatch.ideation-agent"

  # Why: Project scoping is the multi-tenancy mechanism -- critical path
  @key-example @smoke
  Scenario: Scoping a topic to a project
    Given a resolved topic "pipeline.build-started.FEAT-001"
    When I scope it to project "finproxy"
    Then the result should be "finproxy.pipeline.build-started.FEAT-001"

  # Why: Wildcard topics enable fleet-wide subscriptions
  @key-example
  Scenario: Pipeline wildcard topic covers all pipeline events
    When I access Topics.Pipeline.ALL
    Then the value should be "pipeline.>"

  # Why: Agent tool invocation topic -- used for request-reply RPC
  @key-example
  Scenario: Resolving an agent tool invocation topic
    When I resolve Topics.Agents.TOOLS with agent_id "guardkit-factory" and tool_name "lint"
    Then the result should be "agents.guardkit-factory.tools.lint"

  # Why: Approval topics use compound keys -- agent + task
  @key-example
  Scenario: Resolving an approval request topic with agent and task IDs
    When I resolve Topics.Agents.APPROVAL_REQUEST with agent_id "guardkit-factory" and task_id "TASK-001"
    Then the result should be "agents.approval.guardkit-factory.TASK-001"

  # Why: Just-inside boundary -- single-character IDs must still resolve correctly
  @boundary
  Scenario: Resolving topics with minimal-length identifiers
    When I resolve Topics.Pipeline.BUILD_STARTED with feature_id "X"
    Then the result should be "pipeline.build-started.X"

  # Why: Just-inside boundary -- IDs with hyphens and numbers are common in the fleet
  @boundary
  Scenario: Topic resolution handles IDs with hyphens and numbers
    When I resolve Topics.Agents.STATUS with agent_id "my-agent-v2-01"
    Then the result should be "agents.status.my-agent-v2-01"

  # Why: Wildcard topics must use valid NATS wildcard syntax
  @boundary
  Scenario Outline: All wildcard topics end with the NATS wildcard token
    When I access <wildcard_topic>
    Then the value should end with ">"

    Examples:
      | wildcard_topic              |
      | Topics.Pipeline.ALL         |
      | Topics.Pipeline.ALL_BUILDS  |
      | Topics.Agents.STATUS_ALL    |
      | Topics.Agents.TOOLS_ALL     |
      | Topics.Fleet.HEARTBEAT_ALL  |
      | Topics.Fleet.ALL            |

  # Why: Just-outside boundary -- empty feature_id produces invalid NATS subject
  # [ASSUMPTION: confidence=high] Empty string identifiers are rejected by resolve()
  @boundary @negative
  Scenario: Resolving a topic with an empty identifier is rejected
    When I resolve Topics.Pipeline.BUILD_STARTED with feature_id ""
    Then it should raise an error
    And the error should indicate the identifier must not be empty

  # Why: Just-outside boundary -- identifiers with dots would create incorrect subject hierarchy
  # [ASSUMPTION: confidence=medium] Identifiers must not contain dots (NATS subject delimiters)
  @boundary @negative
  Scenario: Resolving a topic with dots in the identifier is rejected
    When I resolve Topics.Pipeline.BUILD_STARTED with feature_id "FEAT.001"
    Then it should raise an error
    And the error should indicate the identifier must not contain dots

  # Why: Just-outside boundary -- identifiers with spaces are invalid NATS subjects
  @boundary @negative
  Scenario: Resolving a topic with spaces in the identifier is rejected
    When I resolve Topics.Pipeline.BUILD_STARTED with feature_id "FEAT 001"
    Then it should raise an error
    And the error should indicate the identifier must not contain spaces

  # Why: Missing template variables must fail explicitly, not produce partial subjects
  @negative @smoke
  Scenario: Resolving a template with a missing variable raises an error
    When I resolve Topics.Pipeline.BUILD_STARTED without providing feature_id
    Then it should raise an error
    And the error should indicate the required variable is missing

  # Why: Extra template variables should be rejected to catch typos early
  @negative
  Scenario: Resolving a template with extra variables raises an error
    When I resolve Topics.Pipeline.BUILD_STARTED with feature_id "FEAT-001" and unknown_var "X"
    Then it should raise an error
    And the error should indicate the variable is unexpected

  # Why: Empty project name would create a leading-dot subject
  # [ASSUMPTION: confidence=high] Empty project names are rejected by for_project()
  @negative
  Scenario: Scoping to an empty project name is rejected
    Given a resolved topic "pipeline.build-started.FEAT-001"
    When I scope it to project ""
    Then it should raise an error
    And the error should indicate the project name must not be empty

  # Why: Project names with dots would collide with NATS subject hierarchy
  # [ASSUMPTION: confidence=medium] Project names follow same rules as identifiers
  @negative
  Scenario: Scoping to a project name with dots is rejected
    Given a resolved topic "pipeline.build-started.FEAT-001"
    When I scope it to project "fin.proxy"
    Then it should raise an error
    And the error should indicate the project name must not contain dots

  # Why: Wildcard tokens in identifiers would create unintended subscriptions
  # [ASSUMPTION: confidence=high] Identifiers must not contain * or > characters
  @negative
  Scenario: Identifiers containing NATS wildcards are rejected
    When I resolve Topics.Agents.STATUS with agent_id "agent-*"
    Then it should raise an error
    And the error should indicate the identifier must not contain wildcard tokens

  # Why: Pipeline topics and EventType enum must stay synchronised
  @edge-case @smoke
  Scenario: Every pipeline topic template corresponds to an EventType
    Given the Topics.Pipeline class
    When I collect all non-wildcard topic templates
    Then every topic should correspond to a value in the EventType enum

  # Why: Agent topic templates and EventType enum must stay synchronised
  @edge-case @smoke
  Scenario: Every agent topic template corresponds to an EventType
    Given the Topics.Agents class
    When I collect all non-wildcard, non-tool topic templates
    Then every topic should correspond to a value in the EventType enum

  # Why: No magic strings -- all topic usage must go through the registry
  @edge-case
  Scenario: No hardcoded topic strings exist outside the registry
    Given the fleet codebase
    When I search for hardcoded topic string patterns like "pipeline.build-" or "agents.status."
    Then no file outside topics.py should contain hardcoded topic strings

  # Why: Resolve and for_project must compose correctly
  @edge-case
  Scenario: Resolving and then project-scoping a topic produces the correct subject
    When I resolve Topics.Pipeline.BUILD_COMPLETE with feature_id "FEAT-001"
    And then scope the result to project "guardkit"
    Then the result should be "guardkit.pipeline.build-complete.FEAT-001"

  # Why: Project-scoped wildcard subscriptions are valid for project-filtered monitoring
  @edge-case
  Scenario: Project-scoping a wildcard topic produces a valid scoped wildcard
    When I scope Topics.Pipeline.ALL to project "finproxy"
    Then the result should be "finproxy.pipeline.>"

  # Why: All topic templates must produce valid NATS subjects when resolved
  @edge-case
  Scenario Outline: All resolved topics are valid NATS subjects
    When I resolve <topic_template> with valid placeholder values
    Then the result should contain only alphanumeric characters, hyphens, dots, and greater-than signs
    And the result should not contain consecutive dots
    And the result should not start or end with a dot

    Examples:
      | topic_template                  |
      | Topics.Pipeline.FEATURE_PLANNED |
      | Topics.Pipeline.BUILD_STARTED   |
      | Topics.Pipeline.BUILD_COMPLETE  |
      | Topics.Agents.STATUS            |
      | Topics.Agents.APPROVAL_REQUEST  |
      | Topics.Agents.COMMAND           |
      | Topics.Agents.TOOLS             |
      | Topics.Fleet.HEARTBEAT          |
      | Topics.Jarvis.COMMAND           |
      | Topics.Jarvis.DISPATCH          |
      | Topics.System.HEALTH            |

  # Why: Topic constants should be accessible as class attributes without instantiation
  @edge-case
  Scenario: Topics class does not require instantiation
    When I access Topics.Pipeline.BUILD_STARTED directly as a class attribute
    Then it should return the topic template string
    And no Topics object needs to be created

  # Why: Approval response topic must be the request topic with ".response" suffix
  @edge-case
  Scenario: Approval response topic extends the request topic
    When I resolve Topics.Agents.APPROVAL_REQUEST with agent_id "factory" and task_id "T1"
    And I resolve Topics.Agents.APPROVAL_RESPONSE with agent_id "factory" and task_id "T1"
    Then the response topic should be the request topic with ".response" appended

  # Why: Newlines or null bytes in identifiers could corrupt NATS protocol framing
  @edge-case @negative
  Scenario: Identifiers containing control characters are rejected
    When I resolve Topics.Agents.STATUS with agent_id containing a newline character
    Then it should raise an error
    And the error should indicate the identifier contains invalid characters

  # Why: Shell metacharacters in project names must not pass through to subjects
  @edge-case @negative
  Scenario: Project name with shell metacharacters is rejected
    When I scope a topic to project "fin;rm -rf"
    Then it should raise an error
    And the error should indicate the project name contains invalid characters

  # Why: Topic constants must not be accidentally overwritten at runtime
  @edge-case
  Scenario: Topic template constants are immutable class attributes
    When I attempt to reassign Topics.Pipeline.BUILD_STARTED to a different value
    Then the assignment should be prevented or the original value should be unchanged

  # Why: All documented namespaces must be present -- missing one means lost coverage
  @edge-case @smoke
  Scenario: All five namespace classes are present in the registry
    When I inspect the Topics class
    Then it should contain Pipeline, Agents, Fleet, Jarvis, and System namespaces

  # Why: Idempotency -- same inputs must always produce same output
  @edge-case
  Scenario: Resolving the same template twice yields identical results
    When I resolve Topics.Pipeline.BUILD_STARTED with feature_id "FEAT-001" twice
    Then both results should be identical
