# Generated by /feature-spec
# Feature: Message Envelope
# Stack: python
# Assumptions: 3 (see message-envelope_assumptions.yaml)
# Generated: 2026-04-08T00:00:00Z

@message-envelope
Feature: Message Envelope
  As a fleet service developer
  I want a base message envelope with versioning and correlation
  So that all NATS messages have a consistent, evolvable wire format

  Background:
    Given the MessageEnvelope schema is available

  # Why: Core construction path -- envelope populates defaults for optional fields
  # [ASSUMPTION: confidence=high] message_id is UUID v4 string per system spec
  @key-example @smoke
  Scenario: Creating an envelope with defaults
    Given no explicit message_id or timestamp
    When I create a MessageEnvelope with source_id "test-agent" and event_type STATUS
    Then message_id should be a valid UUID v4
    And timestamp should be within 1 second of now in UTC
    And version should be "1.0"

  # Why: Wire format must be valid JSON with ISO 8601 timestamps for interop
  @key-example @smoke
  Scenario: Serialising an envelope to JSON
    Given a MessageEnvelope with known field values
    When I serialise it to JSON
    Then the output should be valid JSON
    And timestamp should be in ISO 8601 format
    And all fields should be present in the output

  # Why: Consumers must be able to reconstruct an envelope from the wire format
  @key-example @smoke
  Scenario: Deserialising an envelope from valid JSON
    Given a valid JSON string representing a MessageEnvelope
    When I parse it as a MessageEnvelope
    Then all fields should match the original values
    And message_id should be preserved exactly
    And timestamp should be preserved exactly

  # Why: Correlation ID is the mechanism for linking request-response chains
  @key-example
  Scenario: Correlation ID links related messages
    Given an envelope with correlation_id "session-abc-123"
    When I create a response envelope with the same correlation_id
    Then both envelopes should share the same correlation_id
    And they should have different message_ids
    And they should have different timestamps

  # Why: Project-scoped envelopes support multi-tenancy
  @key-example
  Scenario: Creating an envelope with a project scope
    When I create a MessageEnvelope with project "finproxy" and source_id "guardkit-factory"
    Then the project field should be "finproxy"
    And all other default fields should still be populated

  # Why: Envelope version must follow the documented format
  @boundary
  Scenario: Version field accepts the current version string
    When I create a MessageEnvelope with version "1.0"
    Then the envelope should be valid

  # Why: source_id is the only truly required string field -- verify empty is rejected
  # [ASSUMPTION: confidence=high] source_id minimum length is 1 character (non-empty)
  @boundary @negative
  Scenario: Empty source_id is rejected
    When I create a MessageEnvelope with source_id ""
    Then it should raise a validation error
    And the error should indicate source_id must not be empty

  # Why: event_type must be a valid EventType enum member
  @boundary @negative
  Scenario: Invalid event_type is rejected
    When I create a MessageEnvelope with event_type "nonexistent_event"
    Then it should raise a validation error
    And the error should indicate the event type is not valid

  # Why: Optional fields should accept None gracefully
  @boundary
  Scenario Outline: Optional fields accept None
    When I create a MessageEnvelope with <field> set to None
    Then the envelope should be valid
    And <field> should be None

    Examples:
      | field          |
      | project        |
      | correlation_id |

  # Why: Payload is required -- verify it works with an empty dict (minimal valid payload)
  # [ASSUMPTION: confidence=high] payload type is dict[str, Any] per system spec
  @boundary
  Scenario: Envelope accepts an empty payload dictionary
    When I create a MessageEnvelope with an empty payload
    Then the envelope should be valid
    And the payload should be an empty dictionary

  # Why: message_id uniqueness is critical for deduplication across the fleet
  @boundary
  Scenario: Each envelope generates a unique message_id by default
    When I create 100 MessageEnvelopes without specifying message_id
    Then all 100 message_ids should be unique

  # Why: Forward compatibility -- unknown fields must be silently ignored (ADR XC-schema-versioning)
  @negative @smoke
  Scenario: Deserialising with unknown fields ignores them silently
    Given a JSON string with an extra field "future_field" set to "some_value"
    When I parse it as a MessageEnvelope
    Then it should parse without error
    And the unknown field should not appear in the model

  # Why: source_id is required -- missing it must fail validation
  @negative
  Scenario: Missing required source_id raises a validation error
    Given a JSON string without a source_id field
    When I parse it as a MessageEnvelope
    Then it should raise a validation error
    And the error should mention source_id

  # Why: event_type is required -- missing it must fail validation
  @negative
  Scenario: Missing required event_type raises a validation error
    Given a JSON string without an event_type field
    When I parse it as a MessageEnvelope
    Then it should raise a validation error
    And the error should mention event_type

  # Why: payload is required -- missing it must fail validation
  @negative
  Scenario: Missing required payload raises a validation error
    Given a JSON string without a payload field
    When I parse it as a MessageEnvelope
    Then it should raise a validation error
    And the error should mention payload

  # Why: Envelopes may carry large payloads -- verify no silent truncation
  @edge-case
  Scenario: Envelope handles a large payload without truncation
    Given a payload dictionary with 50 keys and nested structures
    When I create and serialise a MessageEnvelope
    And then deserialise it back
    Then the round-tripped payload should match the original exactly

  # Why: Explicit overrides of defaults must be respected, not overwritten
  @edge-case
  Scenario: Explicit message_id and timestamp override defaults
    Given an explicit message_id "custom-id-12345" and timestamp "2026-01-15T10:30:00Z"
    When I create a MessageEnvelope with these values
    Then message_id should be "custom-id-12345"
    And timestamp should be "2026-01-15T10:30:00Z"

  # Why: Version field enables schema evolution -- must round-trip faithfully
  @edge-case
  Scenario: Future version string round-trips correctly
    Given a MessageEnvelope with version "2.0"
    When I serialise and deserialise it
    Then version should be "2.0"

  # Why: Correlation chains may span many messages -- verify the ID propagates unchanged
  @edge-case
  Scenario: Correlation ID propagates through a chain of messages
    Given a correlation_id "chain-001"
    When I create three envelopes each referencing correlation_id "chain-001"
    Then all three should have correlation_id "chain-001"
    And all three should have distinct message_ids
    And all three should have distinct timestamps

  # Why: Non-ASCII content in payloads must survive serialisation round-trip
  @edge-case
  Scenario: Payload with non-ASCII characters round-trips correctly
    Given a payload containing Unicode characters including emoji and CJK text
    When I create and serialise a MessageEnvelope
    And then deserialise it back
    Then the round-tripped payload should match the original exactly

  # Why: UUID4 generation must be safe under concurrent access
  @edge-case
  Scenario: Concurrent envelope creation produces no message_id collisions
    When I create 1000 MessageEnvelopes concurrently
    Then all 1000 message_ids should be unique

  # Why: Payloads may contain datetime values that need consistent serialisation
  @edge-case
  Scenario: Payload containing datetime values serialises them consistently
    Given a payload with a datetime field as an ISO 8601 string
    When I create and serialise a MessageEnvelope
    And then deserialise it back
    Then the datetime string in the payload should be preserved exactly

  # Why: Cross-version interop -- older producers may omit new optional fields
  @edge-case
  Scenario: Envelope from a different library version parses successfully
    Given a JSON string with extra unknown fields and missing optional fields
    When I parse it as a MessageEnvelope
    Then it should parse without error
    And known required fields should be present
    And unknown fields should be silently ignored
