# Generated by /feature-spec
# Feature: Event Type Schemas
# Stack: python
# Assumptions: 8 (see event-type-schemas_assumptions.yaml)
# Generated: 2026-04-08T00:00:00Z

@event-type-schemas
Feature: Event Type Schemas
  As a fleet service developer
  I want typed payload schemas for every event in the system
  So that producers and consumers share a validated contract with no untyped dictionaries

  Background:
    Given the EventType enum and all payload schemas are available

  # Why: EventType enum is the central registry -- all documented event types must exist
  @key-example @smoke
  Scenario: EventType enum contains all documented event types
    When I inspect the EventType enum
    Then it should contain "feature_planned", "ready_for_dev", "build_started",
      "build_progress", "build_complete", "build_failed", "ticket_updated"
    And it should contain "status", "approval_request", "approval_response",
      "command", "result", "error"
    And it should contain "intent_classified", "dispatch", "agent_result", "notification"
    And it should contain "agent_register", "agent_deregister", "agent_heartbeat"

  # Why: Every EventType must map to a typed payload -- no orphan event types
  @key-example @smoke
  Scenario: Every event type has a corresponding payload class
    Given the EventType enum
    When I check each event type value
    Then there should be a Pydantic payload class for every EventType member

  # Why: EventType is a string enum -- values must be usable as plain strings in NATS messages
  @key-example
  Scenario: EventType values are plain strings
    When I use EventType.BUILD_STARTED as a string
    Then its value should be "build_started"

  # Why: Core pipeline event -- defines the shape of a feature planning announcement
  @key-example @smoke
  Scenario: Creating a valid FeaturePlannedPayload
    Given a feature_id "FEAT-AC1A" with 3 waves and 12 tasks
    When I create a FeaturePlannedPayload with valid fields
    Then feature_id should be "FEAT-AC1A"
    And wave_count should be 3
    And task_count should be 12
    And waves should contain 3 WaveSummary entries

  # Why: Build progress is the most frequently published pipeline event -- must validate bounds
  @key-example @smoke
  Scenario: Creating a valid BuildProgressPayload
    Given a build in progress at wave 2 of 4 with 55.0% overall progress
    When I create a BuildProgressPayload
    Then wave should be 2 and wave_total should be 4
    And overall_progress_pct should be 55.0

  # Why: Build completion is the terminal happy-path event -- must carry PR and summary data
  @key-example @smoke
  Scenario: Creating a valid BuildCompletePayload
    Given a completed build with 10 tasks completed, 0 failed, out of 10 total
    When I create a BuildCompletePayload
    Then tasks_completed should be 10
    And tasks_failed should be 0
    And tasks_total should be 10
    And pr_url should be present when a PR was created

  # Why: Approval flow is critical for human-in-the-loop -- request must carry risk context
  @key-example @smoke
  Scenario: Creating a valid ApprovalRequestPayload
    Given an agent "guardkit-factory" requesting approval for a destructive action
    When I create an ApprovalRequestPayload with risk_level "high"
    Then risk_level should be "high"
    And action_description should describe the action
    And timeout_seconds should default to 300

  # Why: Intent classification drives Jarvis routing -- confidence and target must be present
  @key-example @smoke
  Scenario: Creating a valid IntentClassifiedPayload
    Given user text "build the login page" classified as intent "software.build"
    When I create an IntentClassifiedPayload with confidence 0.92
    Then intent should be "software.build"
    And confidence should be 0.92
    And target_agent should identify the selected agent

  # Why: Fleet registration is the CAN bus pattern -- the manifest must declare capabilities
  @key-example @smoke
  Scenario: Creating a valid AgentRegistrationPayload
    Given an agent "product-owner-agent" with 2 intent capabilities
    When I create an AgentRegistrationPayload
    Then agent_id should be "product-owner-agent"
    And intents should contain 2 IntentCapability entries
    And each intent should have a pattern, signals, confidence, and description

  # Why: Dispatch is how Jarvis routes work to agents -- must carry correlation context
  @key-example
  Scenario: Creating a valid DispatchPayload
    Given an intent "ideate" dispatched to "ideation-agent"
    When I create a DispatchPayload with a correlation_id
    Then target_agent should be "ideation-agent"
    And intent should be "ideate"
    And correlation_id should link back to the original request

  # Why: Build ID must follow the documented naming convention
  # [ASSUMPTION: confidence=high] build_id format is "build-{feature_id}-{YYYYMMDDHHMMSS}" per system spec
  @boundary @smoke
  Scenario: Build ID follows naming convention
    Given a feature_id "FEAT-AC1A"
    When I create a BuildProgressPayload with a valid build_id
    Then build_id should match the pattern "build-FEAT-AC1A-{YYYYMMDDHHMMSS}"

  # Why: Just-inside boundary -- progress at exactly 0.0 (start) and 100.0 (complete)
  @boundary
  Scenario Outline: Build progress percentage at valid bounds
    When I create a BuildProgressPayload with overall_progress_pct <value>
    Then the payload should be valid
    And overall_progress_pct should be <value>

    Examples:
      | value |
      | 0.0   |
      | 50.0  |
      | 100.0 |

  # Why: Just-outside boundary -- progress beyond 100 must be rejected
  @boundary @negative
  Scenario: Build progress percentage above 100 is rejected
    When I create a BuildProgressPayload with overall_progress_pct 100.1
    Then it should raise a validation error
    And the error should indicate the value must be at most 100.0

  # Why: Just-outside boundary -- negative progress must be rejected
  @boundary @negative
  Scenario: Build progress percentage below 0 is rejected
    When I create a BuildProgressPayload with overall_progress_pct -0.1
    Then it should raise a validation error
    And the error should indicate the value must be at least 0.0

  # Why: Intent confidence must be bounded 0.0-1.0 -- just-inside bounds
  @boundary
  Scenario Outline: Intent confidence at valid bounds
    When I create an IntentCapability with confidence <value>
    Then the capability should be valid

    Examples:
      | value |
      | 0.0   |
      | 0.5   |
      | 1.0   |

  # Why: Just-outside boundary -- confidence above 1.0 is nonsensical
  @boundary @negative
  Scenario: Intent confidence above 1.0 is rejected
    When I create an IntentCapability with confidence 1.01
    Then it should raise a validation error
    And the error should indicate confidence must be at most 1.0

  # Why: Just-outside boundary -- negative confidence is nonsensical
  @boundary @negative
  Scenario: Intent confidence below 0.0 is rejected
    When I create an IntentCapability with confidence -0.01
    Then it should raise a validation error
    And the error should indicate confidence must be at least 0.0

  # Why: IntentClassifiedPayload also has a confidence field -- same bounds apply
  @boundary @negative
  Scenario: IntentClassified confidence outside 0.0-1.0 is rejected
    When I create an IntentClassifiedPayload with confidence 1.5
    Then it should raise a validation error

  # Why: Agent status is a Literal type -- only documented values should be accepted
  @boundary
  Scenario Outline: Agent status accepts valid states
    When I create an AgentStatusPayload with state "<state>"
    Then the payload should be valid

    Examples:
      | state              |
      | running            |
      | idle               |
      | awaiting_approval  |
      | error              |
      | paused             |

  # Why: Approval risk_level is constrained -- only low/medium/high are valid
  @boundary
  Scenario Outline: Approval risk level accepts valid values
    When I create an ApprovalRequestPayload with risk_level "<level>"
    Then the payload should be valid

    Examples:
      | level  |
      | low    |
      | medium |
      | high   |

  # Why: Approval decision is constrained -- only documented values
  @boundary
  Scenario Outline: Approval decision accepts valid values
    When I create an ApprovalResponsePayload with decision "<decision>"
    Then the payload should be valid

    Examples:
      | decision |
      | approve  |
      | reject   |
      | defer    |
      | override |

  # Why: Heartbeat status is a Literal -- only documented values
  @boundary
  Scenario Outline: Heartbeat status accepts valid values
    When I create an AgentHeartbeatPayload with status "<status>"
    Then the payload should be valid

    Examples:
      | status   |
      | ready    |
      | busy     |
      | degraded |
      | draining |

  # Why: Registration status is a Literal -- only documented values
  @boundary
  Scenario Outline: Registration status accepts valid values
    When I create an AgentRegistrationPayload with status "<status>"
    Then the payload should be valid

    Examples:
      | status   |
      | ready    |
      | starting |
      | degraded |

  # Why: max_concurrent must be positive -- zero or negative means the agent cannot work
  # [ASSUMPTION: confidence=medium] max_concurrent minimum is 1 based on domain logic
  @boundary @negative
  Scenario: Agent max_concurrent of zero is rejected
    When I create an AgentRegistrationPayload with max_concurrent 0
    Then it should raise a validation error
    And the error should indicate max_concurrent must be at least 1

  # Why: Invalid state string must fail validation -- not silently accepted
  @negative
  Scenario: Invalid agent status is rejected
    When I create an AgentStatusPayload with state "sleeping"
    Then it should raise a validation error
    And the error should indicate the state is not valid

  # Why: Invalid risk level must be caught at schema boundary
  @negative
  Scenario: Invalid approval risk level is rejected
    When I create an ApprovalRequestPayload with risk_level "critical"
    Then it should raise a validation error

  # Why: Invalid approval decision must be caught
  @negative
  Scenario: Invalid approval decision is rejected
    When I create an ApprovalResponsePayload with decision "ignore"
    Then it should raise a validation error

  # Why: Invalid heartbeat status must be caught
  @negative
  Scenario: Invalid heartbeat status is rejected
    When I create an AgentHeartbeatPayload with status "offline"
    Then it should raise a validation error

  # Why: Required fields must not be omittable on pipeline payloads
  @negative
  Scenario: FeaturePlannedPayload requires feature_id
    When I create a FeaturePlannedPayload without feature_id
    Then it should raise a validation error
    And the error should mention feature_id

  # Why: Required fields must not be omittable on build payloads
  @negative
  Scenario: BuildCompletePayload requires build_id
    When I create a BuildCompletePayload without build_id
    Then it should raise a validation error
    And the error should mention build_id

  # Why: Agent registration requires agent_id -- anonymous agents are not allowed
  @negative
  Scenario: AgentRegistrationPayload requires agent_id
    When I create an AgentRegistrationPayload without agent_id
    Then it should raise a validation error
    And the error should mention agent_id

  # Why: Dispatch requires a target agent -- routing with no destination is invalid
  @negative
  Scenario: DispatchPayload requires target_agent
    When I create a DispatchPayload without target_agent
    Then it should raise a validation error
    And the error should mention target_agent

  # Why: Payloads should not use untyped dict at the top level -- enforces contract discipline
  @edge-case @smoke
  Scenario: Payload schemas use strict types not untyped dictionaries
    Given any payload class except generic error
    When I inspect its top-level fields
    Then no field should be an untyped dict[str, Any]
    # Nested dict is acceptable for extensible metadata only

  # Why: All payloads must survive JSON round-trip without data loss
  @edge-case @smoke
  Scenario Outline: Payload round-trips through JSON serialisation
    Given a valid <payload_class> with all fields populated
    When I serialise it to JSON and deserialise it back
    Then all field values should match the original

    Examples:
      | payload_class              |
      | FeaturePlannedPayload      |
      | BuildProgressPayload       |
      | BuildCompletePayload       |
      | BuildFailedPayload         |
      | AgentStatusPayload         |
      | ApprovalRequestPayload     |
      | ApprovalResponsePayload    |
      | IntentClassifiedPayload    |
      | DispatchPayload            |
      | AgentRegistrationPayload   |
      | AgentHeartbeatPayload      |
      | AgentDeregistrationPayload |

  # Why: Defaults must be applied for optional/defaulted fields when not supplied
  @edge-case
  Scenario: Default values are applied when fields are omitted
    When I create an ApprovalRequestPayload without specifying timeout_seconds
    Then timeout_seconds should be 300
    When I create an AgentRegistrationPayload without specifying max_concurrent
    Then max_concurrent should be 1
    When I create an AgentRegistrationPayload without specifying status
    Then status should be "ready"
    When I create an AgentDeregistrationPayload without specifying reason
    Then reason should be "shutdown"

  # Why: BuildFailedPayload must indicate whether the failure is recoverable
  @edge-case
  Scenario: Build failure indicates recoverability
    Given a build that failed due to a transient network error
    When I create a BuildFailedPayload with recoverable set to true
    Then recoverable should be true
    And failure_reason should describe the error

  # Why: WaveSummary and TaskProgress are nested models -- they must validate independently
  @edge-case
  Scenario: Nested models within pipeline payloads validate correctly
    Given a FeaturePlannedPayload with invalid data inside a WaveSummary
    When I attempt to create it
    Then it should raise a validation error pointing to the nested field

  # Why: Forward compatibility -- extra fields on payloads should be tolerated
  # [ASSUMPTION: confidence=high] Payloads use extra="ignore" per ADR XC-schema-versioning
  @edge-case
  Scenario: Payload schemas tolerate unknown fields for forward compatibility
    Given a JSON string for a BuildCompletePayload with an extra field "new_metric"
    When I parse it
    Then it should parse without error
    And the unknown field should be silently ignored

  # Why: IntentCapability is a nested model in registration -- must validate its own constraints
  @edge-case
  Scenario: IntentCapability validates independently within a registration
    Given an AgentRegistrationPayload with an IntentCapability missing its pattern field
    When I attempt to create it
    Then it should raise a validation error pointing to the IntentCapability

  # Why: Heartbeat queue_depth and active_tasks must not be negative
  # [ASSUMPTION: confidence=medium] queue_depth and active_tasks have ge=0 constraint
  @edge-case @boundary
  Scenario: Heartbeat rejects negative queue depth and active tasks
    When I create an AgentHeartbeatPayload with queue_depth -1
    Then it should raise a validation error
    When I create an AgentHeartbeatPayload with active_tasks -1
    Then it should raise a validation error

  # Why: Excessively long strings could cause performance issues during validation
  # [ASSUMPTION: confidence=low] No max_length constraint documented; behaviour is undefined
  @edge-case
  Scenario: Payload handles excessively long string fields
    When I create an AgentStatusPayload with task_description exceeding 10000 characters
    Then the payload should accept the value without constraint
    # No max_length is enforced; consumers should handle display truncation

  # Why: Agent ID is the primary key in the registry -- format must be consistent
  # [ASSUMPTION: confidence=low] agent_id must be a kebab-case identifier (pattern: ^[a-z][a-z0-9-]*$)
  @edge-case @negative
  Scenario: Agent registration rejects invalid agent_id format
    When I create an AgentRegistrationPayload with agent_id "Invalid Agent ID!"
    Then it should raise a validation error
    And the error should indicate agent_id must be a valid kebab-case identifier

  # Why: Overlapping wave progress for the same build could confuse consumers
  @edge-case @boundary
  Scenario: BuildProgressPayload wave number must not exceed wave_total
    When I create a BuildProgressPayload with wave 5 and wave_total 3
    Then it should raise a validation error
    And the error should indicate wave must not exceed wave_total

  # Why: Duplicate agent_id registration is a fleet integrity concern
  @edge-case
  Scenario: Two registrations with the same agent_id are both valid payloads
    Given two AgentRegistrationPayloads with agent_id "ideation-agent"
    When I validate both payloads
    Then both should be valid
    # Conflict resolution is a routing concern, not a schema concern

  # Why: Inconsistent task counts would mislead dashboards and observers
  # [ASSUMPTION: confidence=medium] Schema enforces tasks_completed + tasks_failed == tasks_total
  @edge-case @negative
  Scenario: BuildCompletePayload task counts must be internally consistent
    When I create a BuildCompletePayload with tasks_completed 8, tasks_failed 1, tasks_total 10
    Then it should raise a validation error
    And the error should indicate completed plus failed must equal total

  # Why: Mismatched wave_count and waves list length indicates a producer bug
  # [ASSUMPTION: confidence=medium] Schema enforces wave_count == len(waves)
  @edge-case @negative
  Scenario: FeaturePlannedPayload wave_count must match waves list length
    Given a FeaturePlannedPayload with wave_count 3 but only 2 WaveSummary entries
    When I attempt to create it
    Then it should raise a validation error
    And the error should indicate wave_count must match the number of waves
